languageCode = "en"
languageName = "English"
displayName = ":flag-ie:"
isoCode = "en"
weight = 1
rtl = false

# logo = "img/logo.jpg"
title = "Cian Code"
description = "All Things Computer"
copyright = "&copy; Cian McElhinney"

dateFormat = "2 January 2006"

[author]
  name = "Cian McElhinney"
  image = "img/cian.png"
  headline = "Software Engineer"
  bio = "A little bit about me"
  links = [
    { twitter = "https://twitter.com/username" }
  ]
