languageCode = "en"
languageName = "English"
displayName = ":flag-ie:"
isoCode = "en"
weight = 1
rtl = false

# logo = "img/logo.jpg"
title = "Cian Code"
description = "All Things Computer"
copyright = "&copy; Cian McElhinney"

dateFormat = "2 January 2006"

[author]
  name = "Cian McElhinney"
  image = "img/cian.png"
  headline = "Senior Software Engineer"
  bio = "All Things Computer"
  links = [
    { github = "https://github.com/cianmce" }
    { linkedin = "https://ie.linkedin.com/in/cianmcelhinney" }
  ]
